export const Quotes = [
  'You are more than your hormones — you are whole, powerful, and beautifully resilient.',
  'Healing begins the moment you choose to love your body, not fight it.',
  "PCOS doesn't define your worth — your courage and kindness do.",
  'You are not broken. You are learning to bloom differently.',
  "Your body is not your enemy. It's your partner — listen to it, care for it, and honor its journey.",
  'Every small step toward healing is a victory — even the ones no one else sees.',
  "You've faced imbalance and still stand strong — that's what true balance looks like.",
  "This journey may be slow, but you are moving forward — and that's all that matters.",
  'PCOS may test your strength, but it can never take your spirit.',
  'The storm inside you is teaching you how to rise stronger every single day.',
  "Healing is not linear — it's a dance between patience, progress, and grace.",
  'Your hormones will find their harmony, just as you are finding yours.',
  'Trust the process — every mindful choice brings you closer to balance.',
  'You are allowed to rest. You are allowed to heal at your own pace.',
  "Don't lose hope. Even wildflowers bloom after the harshest seasons.",
  'You are fierce, feminine, and unstoppable — with or without PCOS.',
  'Your body is a miracle in progress — treat it with the love it deserves.',
  'You are rewriting your story — one healthy choice, one brave day at a time.',
  'Hormones can fluctuate, but your worth never does.',
  'You shine brightest when you believe in your strength more than your struggle.',
];
